[package]
name = "tiles"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = "1.5.0"
cosmwasm-std = "1.5.0"
cw-storage-plus = "1.2.0"
cw2 = "1.1.0"
cw721 = "0.18.0"
cw721-base = { version = "0.18.0", features = ["library"] }
schemars = "0.8.11"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sg721 = { version = "3.15.0", features = ["library"] }
sg721-base = { version = "3.15.0", features = ["library"] }
sg-std = "3.2.0"
thiserror = "1.0.31"
sha2 = { version = "0.10.2", default-features = false }
hex = "0.4.3"

[dev-dependencies]
cw-multi-test = "0.20.0"
