[package]
name = "tiles"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = "1.2.1"
cosmwasm-std = { version = "1.2.1", features = ["staking"] }
cosmwasm-storage = "1.2.1"
cw-storage-plus = "1.1.0"
cw2 = "1.1.2"
cw721 = "0.18.0"
cw721-base = { version = "0.18.0", features = ["library"] }
cw-ownable = "0.5.1"
schemars = "0.8.11"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
sg721 = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0", features = ["library"] }
sg721-base = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0", features = ["library"] }
sg2 = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0" }
sg1 = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0" }
sg-std = "3.2.0"
thiserror = "1.0.31"
sha2 = { version = "0.10.8", default-features = false }
hex = "0.4.3"
serde_json = "1.0.108"
vending-factory = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0", features = ["library"] }
vending-minter = { git = "https://github.com/public-awesome/stargaze-contracts", tag = "v3.15.0", features = ["library"] }

[dev-dependencies]
cw-multi-test = { version = "0.16.2", features = ["staking"] }
anyhow = "1.0.75"
sg-multi-test = "3.1.0"
