[package]
name = "tiles"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# Enable backtraces in the binary
backtraces = ["cosmwasm-std/backtraces"]
# Disable entry points when building as a library
library = []
# Enable entry points by default
default = []

[dependencies]
cosmwasm-schema = "1.2.5"
cosmwasm-std = { version = "1.2.5", features = ["staking", "stargate"] }
cw-storage-plus = "1.0.1"
cw2 = "1.0.1"
cw721 = "0.17.0"
cw721-base = { version = "0.17.0", features = ["library"] }
schemars = "0.8.11"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
sg721 = { version = "3.1.0", features = ["library"] }
sg721-base = { version = "3.1.0", features = ["library"] }
sg-metadata = { version = "3.1.0" }
sg-std = "3.1.0"
thiserror = "1.0.38"
lazy_static = "1.4.0"
sha2 = { version = "0.10.2", default-features = false }
hex = "0.4.3"

[dev-dependencies]
cw-multi-test = "0.16.4"
sg-multi-test = "3.1.0"
sg2 = "3.1.0"
anyhow = "1.0.75"
base-factory = { version = "3.15.0" }
vending-factory = { version = "3.15.0", features = ["library"] }
vending-minter = { version = "3.15.0", features = ["library"] }
