use cosmwasm_std::Addr;
use tiles::defaults::constants::{COLLECTION_NAME, COLLECTION_SYMBOL, MINT_PRICE};

use crate::utils::core::app::TestApp;

#[derive(Clone)]
pub struct User {
    pub address: Addr,
}

impl User {
    /// Builds a user from a valid bech32 address. CW721 0.22 validates addresses on
    /// write, so test actors must be real-looking addresses rather than bare labels.
    pub fn new(address: &str) -> Self {
        Self {
            address: Addr::unchecked(address),
        }
    }

    /// Convenience constructor: a deterministic, valid `cosmos1...` address for a label.
    pub fn named(label: &str) -> Self {
        Self {
            address: Addr::unchecked(valid_address(label)),
        }
    }
}

/// Produces an address derived from a label, valid for the test chain.
///
/// `cw-multi-test` validates addresses with real bech32 rules and uses the
/// `cosmwasm` prefix by default, so test actors must be encoded the same way.
pub fn valid_address(label: &str) -> String {
    use bech32::{encode, Bech32, Hrp};
    use sha2::{Digest, Sha256};

    let digest = Sha256::digest(label.as_bytes());
    let hrp = Hrp::parse("cosmwasm").expect("cosmwasm is a valid hrp");
    encode::<Bech32>(hrp, &digest[..20]).expect("bech32 encoding always succeeds")
}

/// The actors used across the test suite.
#[derive(Clone)]
pub struct TestUsers {
    /// Owns the collection, mints tiles and receives the collection share.
    pub buyer: User,
    /// Second actor, used as a colourer or a recipient in transfer tests.
    pub tile_creator: User,
    /// An actor with no funds, to check payment failures.
    pub poor_user: User,
    /// Approved operator in approval/transfer tests.
    pub pixel_operator: User,
    /// Generic third party.
    pub creator: User,
}

impl Default for TestUsers {
    fn default() -> Self {
        Self::new()
    }
}

impl TestUsers {
    pub fn new() -> Self {
        Self {
            buyer: User::new("buyer"),
            tile_creator: User::new("tile_creator"),
            poor_user: User::new("poor_user"),
            pixel_operator: User::new("pixel_operator"),
            creator: User::new("creator"),
        }
    }

    /// Replaces the placeholder labels with addresses generated by the test chain.
    ///
    /// `App::next_address` produces exactly the address format the mock chain accepts,
    /// which CW721 0.22 validates on every write.
    pub fn with_app_addresses(_app: &mut TestApp) -> Self {
        Self {
            buyer: User::named("buyer"),
            tile_creator: User::named("tile_creator"),
            poor_user: User::named("poor_user"),
            pixel_operator: User::named("pixel_operator"),
            creator: User::named("creator"),
        }
    }

    /// Funds every actor except `poor_user`, who is left deliberately empty.
    pub fn init_balances(&self, app: &mut TestApp) {
        for user in [
            &self.buyer,
            &self.tile_creator,
            &self.pixel_operator,
            &self.creator,
        ] {
            crate::utils::core::launchpad::fund(app, &user.address);
        }
    }

    pub fn get_buyer(&self) -> &User {
        &self.buyer
    }

    pub fn get_tile_creator(&self) -> &User {
        &self.tile_creator
    }

    pub fn get_poor_user(&self) -> &User {
        &self.poor_user
    }

    /// Alias kept for readability in tests that reason about actors without funds.
    pub fn poor_user(&self) -> &User {
        &self.poor_user
    }

    pub fn pixel_operator(&self) -> &User {
        &self.pixel_operator
    }

    pub fn tile_contract_creator(&self) -> &User {
        &self.creator
    }

    /// Informational constant used by tests that assert on mint pricing.
    pub fn mint_price(&self) -> u128 {
        MINT_PRICE
    }

    pub fn collection_names(&self) -> (&'static str, &'static str) {
        (COLLECTION_NAME, COLLECTION_SYMBOL)
    }
}
